/* Generated by JSIL v0.2 build 32117. See http://jsil.org/ for more information. */ 
var $asm01 = JSIL.DeclareAssembly("qwf4uaw0, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
JSIL.MakeStaticClass("Program", true);

JSIL.MakeStruct("CustomType", true);

Program.ReturnArgument = function (arg) {
	return arg;
};
Program.Main = function (args) {
	var a = new CustomType();
	a._ctor(1);
	var b = Program.ReturnArgument(a.MemberwiseClone()).MemberwiseClone();
	a.Value = 2;
	System.Console.WriteLine("a={0}, b={1}", a.MemberwiseClone(), b.MemberwiseClone());
	b = Program.ReturnArgument(a.MemberwiseClone()).MemberwiseClone();
	System.Console.WriteLine("a={0}, b={1}", a.MemberwiseClone(), b.MemberwiseClone());
	a.Value = 3;
	System.Console.WriteLine("a={0}, b={1}", a.MemberwiseClone(), b.MemberwiseClone());
};

CustomType.prototype._ctor = function (value) {
	this.Value = value;
};
CustomType.prototype.toString = function () {
	return System.String.Format("{0}", this.Value);
};
CustomType.prototype.Value = 0;


timeout(30); JSIL.Initialize(); JSIL.Host.warnedAboutRunLater = true; var started = elapsed(); Program.Main([]); var ended = elapsed(); print('// elapsed: ' + (ended - started));